services:
  auth:
    image: djeukeu/online-learning-auth:1
    restart: always
    env_file: '.env.auth.dev'
    depends_on:
      mysql:
        condition: service_healthy
    ports:
     - "${AUTH_PORT}:4001"
  course:
    image: djeukeu/online-learning-course:1
    restart: always
    env_file: '.env.course.dev'
    depends_on:
      postgres:
        condition: service_healthy
    ports:
     - "${COURSE_PORT}:4002"
  mysql:
    image: mysql:8.0
    restart: always
    env_file: '.env.auth.dev'
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          '${MYSQL_USER}',
          '-p${MYSQL_ROOT_PASSWORD}',
        ]
  postgres:
    image: postgres:16.9-alpine3.22
    restart: always
    env_file: '.env.course.dev'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
