version: '3.8'

services:
  nginx:
      image: nginx:stable-alpine
      ports:
        - "4000:4000"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - auth
        - course
  auth:
    image: djeukeu/online-learning-auth:1
    restart: always
    env_file: '.env.auth.dev'
    healthcheck:
      test: curl -f http://localhost:4001/health || exit 1
  course:
    image: djeukeu/online-learning-course:1
    restart: always
    env_file: '.env.course.dev'
    healthcheck:
      test: curl -f http://localhost:4002/health || exit 1
