apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
    - name: auth
      protocol: TCP
      port: 4001
      targetPort: 4001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: djeukeu/online-learning-auth:1.0.4
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /health
              port: 4001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 4001
            initialDelaySeconds: 10
            periodSeconds: 20
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: env-auth
                  key: port
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: env-auth
                  key: app_name
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: env-auth
                  key: app_env
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: env-auth
                  key: db_url
            - name: JWT
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: jwt
