apiVersion: v1
kind: Service
metadata:
  name: course-service
spec:
  selector:
    app: course
  type: ClusterIP
  ports:
    - name: http
      protocol: 'TCP'
      port: 4002
      targetPort: 4002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course
  template:
    metadata:
      labels:
        app: course
    spec:
      containers:
        - name: course
          image: djeukeu/online-learning-course:1
          imagePullPolicy: Always
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: env-course
                  key: port
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: env-course
                  key: app_name
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: env-course
                  key: app_env
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: env-course
                  key: db_url
            - name: JWT
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: jwt
