apiVersion: v1
kind: Service
metadata:
  name: course-service
spec:
  selector:
    app: course
  type: ClusterIP
  ports:
    - name: http
      protocol: 'TCP'
      port: 4002
      targetPort: 4002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course
  template:
    metadata:
      labels:
        app: course
    spec:
      containers:
        - name: course
          image: djeukeu/online-learning-course:1.0.6
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /health
              port: 4002
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 4002
            initialDelaySeconds: 10
            periodSeconds: 20
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: env-course
                  key: port
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: env-course
                  key: app_name
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: env-course
                  key: app_env
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: env-course
                  key: db_url
            - name: JWT
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: jwt
