apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment
  type: ClusterIP
  ports:
    - name: http
      protocol: 'TCP'
      port: 4003
      targetPort: 4003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: djeukeu/online-learning-payment:0.0.13
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: env-payment
                  key: port
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: env-payment
                  key: app_name
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: env-payment
                  key: app_env
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: env-payment
                  key: db_url
            - name: JWT
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: jwt
            - name: KAFKA_NAME
              valueFrom:
                configMapKeyRef:
                  name: env-payment
                  key: kafka_name
            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                  name: env-payment
                  key: kafka_broker
            - name: KAFKA_SCHEMA_REGISTRY
              valueFrom:
                configMapKeyRef:
                  name: env-payment
                  key: kafka_schema_registry
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: env-payment
                  key: kafka_topic
            - name: COURSE_EVENT
              valueFrom:
                configMapKeyRef:
                  name: env-payment
                  key: course_event
