name: K8s Deploy
run-name: ${{ github.actor }} triggered the K8s Deploy

on:
  push:
    branches:
      - 'develop'
    paths:
      - 'k8s/**'
      - 'k8s-prod/**'

env:
  EKS_CLUSTER_NAME: ${{secrets.EKS_CLUSTER_NAME}}
  AWS_REGION: ${{secrets.AWS_REGION}}


jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.AWS_REGION}}
      - name: Update kube config
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
      - name: Write k8s env files
        run: |
          cd k8s
          echo '${{ secrets.K8S_ENV }}' > env.yml
          echo '${{ secrets.K8S_AUTH }}' > env-auth.yml
          echo '${{ secrets.K8S_COURSE }}' > env-course.yml
          echo '${{ secrets.K8S_PAYMENT }}' > env-payment.yml
      - name: Deploy k8s
        run: |
          kubectl apply -f k8s
          kubectl apply -f k8s-prod